server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

zuul:
  prefix: /yubing
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicespringcloud-dept
    mydept.path: /mydept/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

#info信息
info:
  app.name: gateway-9527.com
  company.name: www.yubing.tk
  build.artifactId: microservicecloud-zuul-gateway-9527
  build.version: 1.0-SNAPSHOT